"""Central model-data preparation utilities for time-series training."""
from __future__ import annotations

from typing import Literal

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


LEAKAGE_TARGET_COLS = [
    "da_price_eur",
    "afrr_activation_price_vwap_pos",
    "afrr_activation_price_vwap_neg",
    "afrr_activated_mw_pos",
    "afrr_activated_mw_neg",
    "afrr_da_price_spread",
    "afrr_neg_da_price_spread",
]

NON_FEATURE_META_COLS = [
    "is_local_reconstruction_only",
    "data_is_lagged",
    "pit_lagged_column_count",
    # Must be train-fit only; drop any precomputed cluster to avoid leakage.
    "market_state_cluster",
]


def _add_market_state_cluster_feature(
    X_train_df: pd.DataFrame,
    X_test_df: pd.DataFrame,
    n_clusters: int = 4,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Fit scaler + KMeans on train and append cluster ids to train/test.

    Uses only features available in both train and test. If insufficient inputs
    are present, returns the original frames unchanged.
    """
    candidates = [
        "nrv_zscore_24h",
        "grid_stress_index",
        "picasso_flow_rate_lag_1h",
        "picasso_flow_rate_lag_24h",
        "mfrr_active_lag",
    ]
    use_cols = [c for c in candidates if c in X_train_df.columns and c in X_test_df.columns]
    if len(use_cols) < 2:
        return X_train_df, X_test_df

    train_block = X_train_df[use_cols].copy().fillna(0.0)
    test_block = X_test_df[use_cols].copy().fillna(0.0)

    scaler = StandardScaler()
    train_scaled = scaler.fit_transform(train_block)
    test_scaled = scaler.transform(test_block)

    km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    train_cluster = km.fit_predict(train_scaled).astype(float)
    test_cluster = km.predict(test_scaled).astype(float)

    out_train = X_train_df.copy()
    out_test = X_test_df.copy()
    out_train["market_state_cluster"] = train_cluster
    out_test["market_state_cluster"] = test_cluster
    return out_train, out_test


def prepare_model_data(
    df: pd.DataFrame,
    target_col: str,
    model_type: Literal["xgboost", "rf", "linear", "nn"] = "xgboost",
    test_size: float = 0.2,
    add_train_fit_cluster: bool = True,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Prepare leakage-safe train/test tensors for model training.

    This helper is the single entrypoint for model-ready dataset creation across
    tree-based, linear, and neural pipelines.

    Parameters
    ----------
    df : pandas.DataFrame
        Input table containing features, ground-truth targets, and optionally
        `timestamp_utc`.
    target_col : str
        Name of the target column to predict.
    model_type : {"xgboost", "rf", "linear", "nn"}, default "xgboost"
        Controls formatting/scaling:
        - `"xgboost"` / `"rf"`: no feature scaling
        - `"linear"` / `"nn"`: apply `StandardScaler` fit on train only
    test_size : float, default 0.2
        Fraction of rows reserved for test split (chronological tail).
    add_train_fit_cluster : bool, default True
        If True, appends `market_state_cluster` generated by train-only fit of
        `StandardScaler` + `KMeans`, then predicts cluster ids on test.

    Returns
    -------
    tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]
        `(X_train, X_test, y_train, y_test)` prepared for direct model fitting.

    Raises
    ------
    KeyError
        If `target_col` is not present in `df`.
    ValueError
        If `test_size` is invalid, or too few rows remain after filtering.

    Notes
    -----
    - **Target leakage prevention:** unlagged primary market targets
      (e.g., `afrr_vwap_*`, `afrr_activated_*`, spreads) are removed from `X`.
      Additionally, all columns prefixed with `target_` are excluded from `X`
      except the selected `target_col`.
    - **Strict metadata exclusion:** technical QA/meta columns
      (`is_local_reconstruction_only`, `data_is_lagged`,
      `pit_lagged_column_count`) are always removed from `X`.
    - **Chronological split only:** data is sorted by `timestamp_utc` (if
      available) and split sequentially (no shuffling), preventing look-ahead
      bias in power-market time series.
    - **Scaling discipline:** scaler is fit on `X_train` only and then applied to
      `X_test`, avoiding information bleed from test to train.

    Examples
    --------
    >>> X_train, X_test, y_train, y_test = prepare_model_data(
    ...     df, target_col="target_afrr_activation_price_vwap_pos_h1", model_type="xgboost"
    ... )
    >>> X_train_lin, X_test_lin, y_train_lin, y_test_lin = prepare_model_data(
    ...     df, target_col="target_afrr_activation_price_vwap_pos_h1", model_type="linear"
    ... )
    """
    if target_col not in df.columns:
        raise KeyError(f"target_col '{target_col}' not found in dataframe")
    if not (0.0 < test_size < 1.0):
        raise ValueError(f"test_size must be between 0 and 1 (exclusive), got {test_size}")

    data = df.copy()

    if "timestamp_utc" in data.columns:
        ts = pd.to_datetime(data["timestamp_utc"], utc=True, errors="coerce")
        data = data.assign(timestamp_utc=ts).sort_values("timestamp_utc").reset_index(drop=True)
    else:
        data = data.reset_index(drop=True)

    y = pd.to_numeric(data[target_col], errors="coerce")
    keep_mask = y.notna()
    data = data.loc[keep_mask].reset_index(drop=True)
    y = y.loc[keep_mask].reset_index(drop=True)

    if len(data) < 10:
        raise ValueError("Not enough rows after target filtering to perform train/test split.")

    # Remove leakage-prone unlagged market targets from feature matrix.
    drop_from_x = [c for c in LEAKAGE_TARGET_COLS if c in data.columns]
    # Remove strict non-feature metadata columns.
    drop_from_x.extend([c for c in NON_FEATURE_META_COLS if c in data.columns])
    # Targets are supervised labels and must never appear in X.
    drop_from_x.extend([c for c in data.columns if c.startswith("target_")])
    drop_from_x = sorted(set(drop_from_x))
    X = data.drop(columns=drop_from_x, errors="ignore")

    # Keep only numeric features for model readiness.
    X = X.select_dtypes(include=[np.number])

    # Basic, leakage-safe imputation for model compatibility.
    X = X.fillna(X.median(numeric_only=True))

    split_idx = int(len(X) * (1.0 - test_size))
    if split_idx <= 0 or split_idx >= len(X):
        raise ValueError("Invalid split point computed. Check test_size and dataset length.")

    X_train_df = X.iloc[:split_idx].copy()
    X_test_df = X.iloc[split_idx:].copy()
    y_train = y.iloc[:split_idx].to_numpy(dtype=float)
    y_test = y.iloc[split_idx:].to_numpy(dtype=float)

    if add_train_fit_cluster:
        X_train_df, X_test_df = _add_market_state_cluster_feature(X_train_df, X_test_df)

    X_train = X_train_df.to_numpy(dtype=float)
    X_test = X_test_df.to_numpy(dtype=float)

    mt = model_type.lower()
    if mt in {"xgboost", "rf"}:
        return X_train, X_test, y_train, y_test
    if mt in {"linear", "nn"}:
        # Scale only explicit lag features to preserve interpretability of
        # calendar/flag/meta-derived magnitudes.
        lag_cols = [i for i, c in enumerate(X_train_df.columns) if "_lag_" in c]
        X_train_scaled = X_train.copy()
        X_test_scaled = X_test.copy()
        if lag_cols:
            scaler = StandardScaler()
            X_train_scaled[:, lag_cols] = scaler.fit_transform(X_train[:, lag_cols])
            X_test_scaled[:, lag_cols] = scaler.transform(X_test[:, lag_cols])
        return X_train_scaled, X_test_scaled, y_train, y_test

    raise ValueError(f"Unsupported model_type '{model_type}'. Use xgboost, rf, linear, or nn.")
